-- SQL to insert students from attendance lists into Supabase
-- Academic Year: 2025-26
-- Programs: BE VIII, SE IV, TE VI
-- Total Students: 229

INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0002', 'Siddhi Shinde', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0003', 'Asmita Jadhav', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0004', 'Amrita De', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0005', 'Vainavi Lad', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0006', 'MRUGANK VICHARE', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0007', 'Neetish Dhavgaye', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0008', 'Arpit Hande', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0009', 'Renuka Kadam', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0010', 'Insha Khan', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0011', 'Komal Sandip Jadhav', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0012', 'Dipika Dattatray Gadekar', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0013', 'Abhijeet pomane', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0014', 'Ganesh Tukaram Waghmare', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0015', 'Saurav Sanjay mate', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0016', 'Anuj Gill', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0018', 'Yash Vivek Sawant', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0022', 'Yash Rupesh Pagar', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0025', 'Anushka Thacore', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0026', 'Prajakta Nitin Chorge', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0027', 'Sahil Shangloo', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0028', 'Sankalp Rajendra Wani', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0029', 'Pratik Jitendra Sawant', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0030', 'Rasika Jade', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0031', 'Vinay Uttam Pawar', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0032', 'Ruchika Chavan', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0033', 'Tejas Kunde', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0034', 'Tanvi Kharade', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0035', 'Abhijit Vinayak Palve', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0036', 'Harshal sonawane', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0037', 'Sonal Solaskar', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0038', 'Himanshu Narendra Pathak', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0039', 'Rutuja Sargar', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0040', 'Roshan Vilas Khatal', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0041', 'Abhishek Deepak Pawaskar', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0042', 'Rohan Shatrughan Bage', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0043', 'Arya Chavan', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0044', 'Abhinav Upadhyay', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0045', 'Pavankumar Fasale', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0046', 'Divya Poojari', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0047', 'Harsh Rawte', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0048', 'Saiel Lad', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0049', 'Arkan Khan', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0050', 'Aryan kelshikar', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0051', 'Rakshit Naik', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0053', 'Harshada Chaudhari', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0054', 'Yash Newalkar', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0055', 'Sanskruti Kalpesh Mistry', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0056', 'Kalpak Kulkarni', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0057', 'Siddhesh Kadam', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0058', 'Tanmay Thakare', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0059', 'Gargi Kshirsagar', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0060', 'Arpit Gaikwad', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0062', 'Lekhanshu Ganveer', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0063', 'Rugved Mokashi', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0064', 'Parth Kale', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0065', 'Jayant Pravin Dethe', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0066', 'Omkar Mane', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0067', 'Abhishek Pal', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0068', 'Lakhan Subhash Kale', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0069', 'Karan goyal', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0070', 'Rutuja Harish Bangera', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0071', 'Parth gupta', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0072', 'Atharv Mahale', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0073', 'Om Alve', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0074', 'Ajay Ramkisan mali', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0075', 'Bhagyoday bade', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0076', 'Aditi Rao', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0077', 'Riya Singh', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0078', 'Sampurna Prabhu', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('22101A0079', 'Sujal Lambour', 'BE VIII', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0002', 'SHAYAAN CHITRE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0006', 'SAMEER  JAGTAP', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0007', 'DARPAN PHADKE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0010', 'FAAEQ SAYED', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0011', 'MOHAMMED TALHA KHAN', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0013', 'VIRAJ BHADANGE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0014', 'ABDUL HAKIM SHAIKH', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0015', 'MAYURI KINAKE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0016', 'SACHIN YADAV', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0017', 'ABEDAN BISWAL', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0018', 'NAVEEN  KALDATE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0020', 'NINAD GABHALE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0021', 'TANAYA LOKHANDE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0022', 'SAIRAJ KHANDAGALE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0023', 'ABHIJEET SADAMATE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0024', 'SAYALI ANDHALE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0025', 'AMAAN SIDDIQUE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0026', 'UDAY MAHAJAN', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0027', 'SHIVAM  MISHRA', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0028', 'MANTHAN DHOKTE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0029', 'AVINASH PADVI', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0030', 'ASHWIN AMBASTHA', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0031', 'SHREYA SURVE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0032', 'CHANDANI SAW', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0033', 'NIKHIL SAKPAL', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0034', 'YASH MORE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0035', 'SUMIT GHATUL', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0036', 'ADITYA SHINDE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0037', 'SOHAM DUGADE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0038', 'AADITYA SURYAWANSHI', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0039', 'ATHARV GHORPADE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0040', 'OM RATHOD', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0041', 'ABUBAKAR AHMED', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0042', 'SRUSHTI BANUGADE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0043', 'RITIK JAIN', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0045', 'SHRAVNI ANDHALE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0046', 'SRUSHTI PADVI', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0047', 'KAVITA GUPTA', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0048', 'SANSKRUTI PALKAR', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0049', 'SIDDHARTH  SHINDE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0050', 'CHIRAG POOJARY', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0051', 'MOHAMMAD ARHAAM SHAIKH', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0052', 'AAYUSH BHOGALE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0053', 'PRANIT WAGHMARE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0054', 'MARTAND JADHAV', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0055', 'DARSHAN PALKAR', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0056', 'ANKUR  KESARKAR', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0057', 'OM  PAWAR', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0058', 'AENOSE JOEL GURRALA', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0060', 'ROMIN KHAN', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0061', 'GAURAV GHUDE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0062', 'MUNJA KADAM', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0063', 'FARHAN AHMAD KHAN', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0065', 'YASH PATIL', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0066', 'JENISH  SHAH', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0067', 'SWARA BIRJE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0068', 'SAMPRATI  TIKONE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0069', 'OM YEWALE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0070', 'KEDAR SAWANT', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0071', 'SAUKHYA GAIKWAD', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0072', 'LOKESH  MARATHE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0073', 'ADVAY TONGAONKAR', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0074', 'SRUSHTI CHAVAN', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0075', 'AYUSH PATIL', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0076', 'YASH  BAKALE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0077', 'ISHAN GURAV', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0078', 'MANTHAN SHAH', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0079', 'PREM YELWANDE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0080', 'JIYA KANOJIA', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A0081', 'ADITYA DANDAGVHAL', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('25101A2001', 'DEEPALI GANACHARI', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('25101A2002', 'SNEHAL PATIL', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('25101A2003', 'GRISHMA PATIL', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('25101A2004', 'TEJAL SURKULE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('25101A2005', 'SARTHAK SONAWANE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('25101A2006', 'VAISHNAVI KUNTE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('25101A2007', 'ANUSHKA GADHAVE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('25101A2008', 'TANVI JAWARE', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('25101A2009', 'SHRAVANI KADAM', 'SE IV', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0001', 'MAYANK EKBOTE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0002', 'PRANJALI NANDKAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0005', 'NIRANJANA CHAVAN', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0006', 'ARYAN DALAL', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0007', 'SANKHYA LONDHE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0008', 'SWAYAM BALLAL', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0009', 'VED THOMBRE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0010', 'SOHAM WAYANGANKAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0011', 'AMAN VARMA', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0012', 'TEJAS KHANDARE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0013', 'SARVESH CHOUDHARY', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0014', 'JALAJA YELVE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0015', 'ARUNIMA PILLAI', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0016', 'AKANKSHA JADHAV', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0017', 'SOHAN BHANGARE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0018', 'SUJAL JAKAKURE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0019', 'ROHIT GUPTA', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0020', 'BUSHRA SAEED', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0021', 'ALOK MESHRAM', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0022', 'ARYANT  JADHAV', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0023', 'KASHYAP NATHOO', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0024', 'RITESH PAWAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0025', 'ANSH  KUDALKAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0026', 'RITIKA VARADKAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0027', 'DIKSHA VAREKAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0028', 'KAMRAAN MULANI', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0029', 'SHUBHAM YADAV', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0030', 'OMPRAKASH MAURYA', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0031', 'SHUBHAM GAJARE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0032', 'SHREYA GAONKAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0033', 'SHREYAS KHOBRAGADE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0034', 'KANHAIYALAL YADAV', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0035', 'ARADHYA JADHAV', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0036', 'ATHARV JADHAV', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0037', 'TEJAS SHINGTE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0038', 'DEVEN BAGADE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0039', 'KIRAT SINGH CHAWLA', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0041', 'ARYAN VARMA', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0042', 'ASMITA PAL', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0043', 'ATHARVA KENI', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0045', 'ATHARVA DESHMUKH', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0047', 'SHARWAN SHINGADE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0048', 'ABHISHEK WALI', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0049', 'SAIF SIDDIQUI', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0050', 'JATIN RATHOD', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0051', 'YASHODHAN RAJAPKAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0052', 'YADNIKA PASHTE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0053', 'CHAITRALI  MITHBAWKAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0054', 'AYUSH SHEWALE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0055', 'HARSHAD KANERKAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0056', 'SHREYAS KHARAT', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0059', 'AARYA KHAIRE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0060', 'PRITRAJ CHAUDHARY', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0061', 'SAIRAJ NAIKDHURE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0062', 'SHUBHAM WAVRE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0063', 'SARTHAK GAIKAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0064', 'MANORANJAN PAUL', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0065', 'RISHABH HEGDE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0067', 'KAIVALYA GHARAT', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0068', 'OMKAR MADAV', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0070', 'VIGHNARAJENDRA  KAKADE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0071', 'AYUSH GUJAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0072', 'PRITIVARDHINI SANGAVE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0073', 'SWARALI MAHISHI', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0074', 'TANAYA SALUNKE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0075', 'SWAYAM PAWAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0076', 'DEVEN HADKAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23101A0077', 'ISHWARI PANDIT', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23102A0051', 'SOHAM PAWAR', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('23108A0031', 'IRA VAIDYA', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A2001', 'ATHARVA GITAYE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A2002', 'APURV DESHMUKH', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A2003', 'PRITI CHAVAN', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A2004', 'SWATI MANE', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A2005', 'ANISH BANDAL', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A2006', 'VIPUL RAGHATWAN', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A2007', 'MUKTA REDIJ', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A2008', 'ARYAN CHAVAN', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A2009', 'ADITYA MULEY', 'TE VI', NOW());
INSERT INTO students (roll_no, name, program, created_at) VALUES ('24101A2010', 'ANKITA PAWAR', 'TE VI', NOW());