-- SQL to insert all students into Supabase
-- Academic Year: 2025-26
-- Multiple programs and divisions
-- Total Students: 586

INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0002', 'Siddhi Shinde', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0003', 'Asmita Jadhav', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0004', 'Amrita De', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0005', 'Vainavi Lad', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0006', 'MRUGANK VICHARE', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0007', 'Neetish Dhavgaye', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0008', 'Arpit Hande', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0009', 'Renuka Kadam', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0010', 'Insha Khan', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0011', 'Komal Sandip Jadhav', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0012', 'Dipika Dattatray Gadekar', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0013', 'Abhijeet pomane', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0014', 'Ganesh Tukaram Waghmare', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0015', 'Saurav Sanjay mate', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0016', 'Anuj Gill', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0018', 'Yash Vivek Sawant', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0022', 'Yash Rupesh Pagar', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0025', 'Anushka Thacore', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0026', 'Prajakta Nitin Chorge', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0027', 'Sahil Shangloo', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0028', 'Sankalp Rajendra Wani', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0029', 'Pratik Jitendra Sawant', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0030', 'Rasika Jade', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0031', 'Vinay Uttam Pawar', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0032', 'Ruchika Chavan', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0033', 'Tejas Kunde', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0034', 'Tanvi Kharade', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0035', 'Abhijit Vinayak Palve', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0036', 'Harshal sonawane', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0037', 'Sonal Solaskar', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0038', 'Himanshu Narendra Pathak', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0039', 'Rutuja Sargar', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0040', 'Roshan Vilas Khatal', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0041', 'Abhishek Deepak Pawaskar', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0042', 'Rohan Shatrughan Bage', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0043', 'Arya Chavan', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0044', 'Abhinav Upadhyay', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0045', 'Pavankumar Fasale', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0046', 'Divya Poojari', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0047', 'Harsh Rawte', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0048', 'Saiel Lad', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0049', 'Arkan Khan', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0050', 'Aryan kelshikar', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0051', 'Rakshit Naik', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0053', 'Harshada Chaudhari', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0054', 'Yash Newalkar', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0055', 'Sanskruti Kalpesh Mistry', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0056', 'Kalpak Kulkarni', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0057', 'Siddhesh Kadam', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0058', 'Tanmay Thakare', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0059', 'Gargi Kshirsagar', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0060', 'Arpit Gaikwad', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0062', 'Lekhanshu Ganveer', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0063', 'Rugved Mokashi', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0064', 'Parth Kale', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0065', 'Jayant Pravin Dethe', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0066', 'Omkar Mane', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0067', 'Abhishek Pal', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0068', 'Lakhan Subhash Kale', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0069', 'Karan goyal', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0070', 'Rutuja Harish Bangera', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0071', 'Parth gupta', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0072', 'Atharv Mahale', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0073', 'Om Alve', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0074', 'Ajay Ramkisan mali', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0075', 'Bhagyoday bade', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0076', 'Aditi Rao', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0077', 'Riya Singh', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0078', 'Sampurna Prabhu', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101A0079', 'Sujal Lambour', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A2001', 'Shlok Banubakode', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A2002', 'Asmika Panchal', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A2003', 'Vismay vikas whavle', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A2004', 'Vaishnavi Rajguru', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A2005', 'Amey Sandip Gaikwad', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A2006', 'Mansi Sitaram Burud', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A2007', 'Kunal Subhash Mundhe', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A2008', 'Niriksha Nitendra Shivalkar', 'BE VIII', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0001', 'Sanjana Kurade', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0002', 'Sasmit Sakpal', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0003', 'Atharva Ajagekar', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0004', 'Shravani Jayprakash Borji', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0005', 'Sarthak Borde', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0006', 'Sahil Sanjay Sakpal', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0007', 'Nilay Pandya', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0008', 'Chinmay Tikole', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0009', 'Arya Pandey', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0010', 'Ayush Bitla', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0011', 'Sneha Brahmane', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0012', 'Atharva Jamdade', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0013', 'Mansi Patil', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0014', 'Tejas Tanaji Shinde', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0015', 'Anish Pimple', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0016', 'Sanika Jade', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0017', 'Ameya Mahajan', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0018', 'Dip Sonu Sawant', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0019', 'Sumit jaywant bhoir', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0022', 'Mohit koli', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0023', 'Sahil Ansari', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0025', 'Mohd Ismail Quadri', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0026', 'Halim Shaikh', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0027', 'Riya Pal', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0028', 'Eshaan Padhye', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0029', 'Siddhesh Sunil Gharat', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0030', 'Aniket Panchal', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0031', 'Pradyumna Kale', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0032', 'Sahil Hemant Thale', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0034', 'Ishwari Raut', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0036', 'Aditya Shahi', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0037', 'Aneesh Angane', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0038', 'Akshay Gabhane', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0039', 'Atharv Patil', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0040', 'Gaurav Khanna', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0041', 'Tanishka Kasliwal', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0042', 'Shubham Shinde', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0043', 'Mayur Parab', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0045', 'Mangeshkumar Shah', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0046', 'Amaan Kasu', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0049', 'Om Ramesh Singh', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0050', 'Pavankumar Singh', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0051', 'Rishil Ramdhumal', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0052', 'Mrunal Sangade', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0053', 'Soham Ghogare', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0054', 'Soham Bagayatkar', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0055', 'Varun Kirkire', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0056', 'Atharva Urankar', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0057', 'Mrunmayee Yadav', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0058', 'Aarya Patil', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0059', 'Rushikesh Bandiwadekar', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0060', 'Srushti jadhav', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0061', 'Sairaj Ambre', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0062', 'Rashmi Sahu', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0063', 'Parth Karande', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0064', 'Aareian Nakhawa', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0065', 'Atharva Dali', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0066', 'Arya Sanjay Sadigale', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0067', 'Ayush Singh', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0068', 'Tejas Dipak Chorage', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0069', 'Saloni Varekar', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0070', 'Ishaan Dhuri', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0071', 'Sahil Naik', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0072', 'Ganesh Choudhary', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22102B0029', 'Soham Mhatre', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22104B0060', 'Aditya Ram Vemuri', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B2001', 'Om sunil sagvekar', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B2002', 'Sanjay Mahabal', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B2003', 'Aditya Chikane', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B2004', 'Medha Avhad', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101b2005', 'Rajat yadav', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B2006', 'Chinmayee Avinash Deshmukh', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B2007', 'Vaishnavi dhanaji karape', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B2008', 'Aishwarya Prakash Huddar', 'BE VIII', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0002', 'SHAYAAN CHITRE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0006', 'SAMEER  JAGTAP', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0007', 'DARPAN PHADKE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0010', 'FAAEQ SAYED', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0011', 'MOHAMMED TALHA KHAN', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0013', 'VIRAJ BHADANGE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0014', 'ABDUL HAKIM SHAIKH', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0015', 'MAYURI KINAKE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0016', 'SACHIN YADAV', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0017', 'ABEDAN BISWAL', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0018', 'NAVEEN  KALDATE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0020', 'NINAD GABHALE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0021', 'TANAYA LOKHANDE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0022', 'SAIRAJ KHANDAGALE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0023', 'ABHIJEET SADAMATE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0024', 'SAYALI ANDHALE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0025', 'AMAAN SIDDIQUE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0026', 'UDAY MAHAJAN', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0027', 'SHIVAM  MISHRA', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0028', 'MANTHAN DHOKTE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0029', 'AVINASH PADVI', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0030', 'ASHWIN AMBASTHA', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0031', 'SHREYA SURVE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0032', 'CHANDANI SAW', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0033', 'NIKHIL SAKPAL', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0034', 'YASH MORE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0035', 'SUMIT GHATUL', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0036', 'ADITYA SHINDE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0037', 'SOHAM DUGADE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0038', 'AADITYA SURYAWANSHI', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0039', 'ATHARV GHORPADE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0040', 'OM RATHOD', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0041', 'ABUBAKAR AHMED', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0042', 'SRUSHTI BANUGADE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0043', 'RITIK JAIN', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0045', 'SHRAVNI ANDHALE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0046', 'SRUSHTI PADVI', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0047', 'KAVITA GUPTA', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0048', 'SANSKRUTI PALKAR', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0049', 'SIDDHARTH  SHINDE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0050', 'CHIRAG POOJARY', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0051', 'MOHAMMAD ARHAAM SHAIKH', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0052', 'AAYUSH BHOGALE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0053', 'PRANIT WAGHMARE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0054', 'MARTAND JADHAV', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0055', 'DARSHAN PALKAR', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0056', 'ANKUR  KESARKAR', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0057', 'OM  PAWAR', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0058', 'AENOSE JOEL GURRALA', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0060', 'ROMIN KHAN', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0061', 'GAURAV GHUDE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0062', 'MUNJA KADAM', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0063', 'FARHAN AHMAD KHAN', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0065', 'YASH PATIL', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0066', 'JENISH  SHAH', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0067', 'SWARA BIRJE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0068', 'SAMPRATI  TIKONE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0069', 'OM YEWALE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0070', 'KEDAR SAWANT', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0071', 'SAUKHYA GAIKWAD', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0072', 'LOKESH  MARATHE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0073', 'ADVAY TONGAONKAR', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0074', 'SRUSHTI CHAVAN', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0075', 'AYUSH PATIL', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0076', 'YASH  BAKALE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0077', 'ISHAN GURAV', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0078', 'MANTHAN SHAH', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0079', 'PREM YELWANDE', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0080', 'JIYA KANOJIA', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A0081', 'ADITYA DANDAGVHAL', 'SE IV', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0001', 'MOHAMMED YUSUF SAYED', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0004', 'GAYATRI CHAND', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0005', 'DHANRAJ MOGERA', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0006', 'VARENNYA  POPHALI', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0007', 'SHIVANSHU RAI', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0008', 'RITESH ZAGADE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0009', 'GAURI KHATOKAR', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0013', 'KARTIK MAILARAM', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0014', 'SAHIL SANAP', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0016', 'VAISHNAVI BAGADE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0017', 'DEVEN MAGAR', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0018', 'PREM RANMALE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0019', 'SWAYAM  SONAVNE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0021', 'JAGDISH  BAKLE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0022', 'SUMIT SURWASE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0023', 'SAMRUDDHI KHADE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0025', 'KRISH PATIL', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0026', 'SHREESH KHAMKAR', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0027', 'PRANITHA SHETTY', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0028', 'SUJAL TIWARI', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0029', 'PRADNYA CHAUDHARI', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0030', 'SARTHAK KANE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0031', 'SHRIHARI DAVARE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0032', 'MRUNALI DEVARE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0034', 'SHREYAS  CHOUDHARY', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0035', 'HIMANSHU CHOYAL', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0036', 'PARTH KINAGE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0037', 'PRIYANSHU GUPTA', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0038', 'SHUBHAM MAHANWAR', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0040', 'VARAD DALVI', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0042', 'SNEHA BHUNDERE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0043', 'OMKAR BENGALI', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0044', 'RONAK BODDU', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0045', 'VIVEK KHANDARE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0046', 'RASHI KHUTWAD', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0047', 'VISHAL PRAJAPATI', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0048', 'MOHD ALTAMASH ANSARI', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0049', 'MEET ALSHI', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0051', 'VEDANGI POKHARKAR', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0052', 'ATHARV RAUT', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0053', 'PHALGUNI DHOPTE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0054', 'IMRAN SHAIKH', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0055', 'RONAK GHODE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0056', 'AMOL PATIL', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0057', 'BHUSHAN BOROLE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0058', 'ROHIT RATHOD', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0061', 'ADITYA SARKATE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0063', 'AASHUTOSH MAHAJAN', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0064', 'NIKHAT MOMIN', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0065', 'SWAPNIL BHABAL', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0068', 'YASH JADHAV', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0070', 'SHARWARI LOHATE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0071', 'TANISHKA  MANTRI', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0072', 'ADITYA PATRA', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0073', 'ADITYA  BHOGAVKAR', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0074', 'KRISH  GHAG', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0075', 'SNIGDHA SEEPA', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0076', 'TANVEE KAMBLE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0077', 'KRISHNA TIWARI', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0078', 'SHRIYA VIBHUTE', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0079', 'PEARL RATHOD', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0080', 'MANTHAN RATHI', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0081', 'SAIRAJ PATEKAR', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0082', 'ATHARVA GAIKWAD', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B0083', 'MALHAAR NIKAM', 'SE IV', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0002', 'SHREEMAN KUMAR', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0003', 'OMKAR  PADHI', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0004', 'DARSHAN KERKAR', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0006', 'ATHARVA CHAVAN', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0007', 'MRUNAL WARANGE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0008', 'ATHARVA BHOSALE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0010', 'VEDANT CHAVAN', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0011', 'SAKSHI ROUNDHAL', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0013', 'BURHANUDDIN LOKHANDWALA', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0014', 'SHREYA MURKAR', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0015', 'ASHWIN AGRAWAL', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0016', 'NEHA NAYAK', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0017', 'ANKITA SHANBHAG', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0018', 'SHWETA GUPTA', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0019', 'SHRIYA  SAWANT', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0020', 'ARYAN KELKAR', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0021', 'PRATHAMESH SALUNKHE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0022', 'ARYAN ACHARYA', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0024', 'PRANAY  UPADHYAY', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0025', 'ROHAN SINGH', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0026', 'SUSHANT NIRATE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0027', 'DAKSH PARDESHI', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0030', 'HUZAIFAH SHAIKH', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0031', 'RITIKA SHARMA', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0032', 'JAYA PATIL', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0033', 'DEVANGINI JADHAV', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0034', 'AAYUSH ABHYANKAR', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0035', 'JAY  JADHAV', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0036', 'SHANTANU DALVI', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0037', 'HARSH SURANA', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0038', 'SHLOK JAIN', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0039', 'ASHUTOSH TRIPATHI', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0040', 'SAURABH  LUBAL', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0041', 'OM THAKUR', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0042', 'SAKSHI JADHAV', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0043', 'RAHUL AMBHORE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0044', 'SUBHADEEP MONDAL', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0045', 'SHARVIL CHANDURKAR', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0046', 'PUSHKAR CHAVAN', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0048', 'GAUTAM KESHARWANI', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0051', 'GAURAV TIWARI', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0052', 'KHUSH JAIN', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0053', 'VIVEK RAMINA', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0054', 'SAWANKUMAR GUPTA', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0056', 'ASAWARI NAVLE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0057', 'RUHAAN JOSHI', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0058', 'SARTHAK BONGANE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0059', 'KASHYAP SAKHARE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0060', 'JASWANDI VICHARE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0061', 'PRANAY BELNEKAR', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0062', 'RUDRA JAIN', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0063', 'SHLOK SHINDE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0064', 'NIRMITI SAWANT', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0065', 'AYUSH KAMBLE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0066', 'SHAMITA  CHAVAN', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0067', 'DURVA MALUSARE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0068', 'VARUN SINGH', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0069', 'DEVANSH DHAWADE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0070', 'ANAGHA VICHARE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0071', 'ADITYA  KANNOJIYA', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0072', 'PRERNA CHAVAN', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0073', 'AARUSH NALAVADE', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0074', 'MRUNALI PATIL', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0075', 'SHAAN JANA', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0076', 'SHUBHAM SINGH', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0077', 'VEDANT TULASKAR', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C0078', 'DAKSH MALUSKAR', 'SE IV', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0001', 'MAYANK EKBOTE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0002', 'PRANJALI NANDKAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0005', 'NIRANJANA CHAVAN', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0006', 'ARYAN DALAL', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0007', 'SANKHYA LONDHE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0008', 'SWAYAM BALLAL', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0009', 'VED THOMBRE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0010', 'SOHAM WAYANGANKAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0011', 'AMAN VARMA', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0012', 'TEJAS KHANDARE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0013', 'SARVESH CHOUDHARY', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0014', 'JALAJA YELVE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0015', 'ARUNIMA PILLAI', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0016', 'AKANKSHA JADHAV', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0017', 'SOHAN BHANGARE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0018', 'SUJAL JAKAKURE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0019', 'ROHIT GUPTA', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0020', 'BUSHRA SAEED', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0021', 'ALOK MESHRAM', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0022', 'ARYANT  JADHAV', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0023', 'KASHYAP NATHOO', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0024', 'RITESH PAWAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0025', 'ANSH  KUDALKAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0026', 'RITIKA VARADKAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0027', 'DIKSHA VAREKAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0028', 'KAMRAAN MULANI', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0029', 'SHUBHAM YADAV', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0030', 'OMPRAKASH MAURYA', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0031', 'SHUBHAM GAJARE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0032', 'SHREYA GAONKAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0033', 'SHREYAS KHOBRAGADE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0034', 'KANHAIYALAL YADAV', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0035', 'ARADHYA JADHAV', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0036', 'ATHARV JADHAV', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0037', 'TEJAS SHINGTE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0038', 'DEVEN BAGADE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0039', 'KIRAT SINGH CHAWLA', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0041', 'ARYAN VARMA', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0042', 'ASMITA PAL', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0043', 'ATHARVA KENI', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0045', 'ATHARVA DESHMUKH', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0047', 'SHARWAN SHINGADE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0048', 'ABHISHEK WALI', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0049', 'SAIF SIDDIQUI', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0050', 'JATIN RATHOD', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0051', 'YASHODHAN RAJAPKAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0052', 'YADNIKA PASHTE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0053', 'CHAITRALI  MITHBAWKAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0054', 'AYUSH SHEWALE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0055', 'HARSHAD KANERKAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0056', 'SHREYAS KHARAT', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0059', 'AARYA KHAIRE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0060', 'PRITRAJ CHAUDHARY', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0061', 'SAIRAJ NAIKDHURE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0062', 'SHUBHAM WAVRE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0063', 'SARTHAK GAIKAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0064', 'MANORANJAN PAUL', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0065', 'RISHABH HEGDE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0067', 'KAIVALYA GHARAT', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0068', 'OMKAR MADAV', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0070', 'VIGHNARAJENDRA  KAKADE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0071', 'AYUSH GUJAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0072', 'PRITIVARDHINI SANGAVE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0073', 'SWARALI MAHISHI', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0074', 'TANAYA SALUNKE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0075', 'SWAYAM PAWAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0076', 'DEVEN HADKAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101A0077', 'ISHWARI PANDIT', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23102A0051', 'SOHAM PAWAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23108A0031', 'IRA VAIDYA', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A2001', 'ATHARVA GITAYE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A2002', 'APURV DESHMUKH', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A2003', 'PRITI CHAVAN', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A2004', 'SWATI MANE', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A2005', 'ANISH BANDAL', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A2006', 'VIPUL RAGHATWAN', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A2007', 'MUKTA REDIJ', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A2008', 'ARYAN CHAVAN', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A2009', 'ADITYA MULEY', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101A2010', 'ANKITA PAWAR', 'TE VI', 'A', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0002', 'VISHANT GAWALI', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0003', 'KESHAV VERMA', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0004', 'SAMIKSHA DALVI', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0005', 'DHRUV TIKHANDE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0006', 'ISHWAR GARJE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0007', 'SNEHA AJAGEKAR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0008', 'MADHUR PATIL', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0009', 'JAY  JANGAM', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0010', 'ATHARV PETKAR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0011', 'OM KHEDKAR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0012', 'SOHAM THAKUR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0013', 'AKASH MISALE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0014', 'ZAYAN SHAIKH', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0015', 'RUDRAPRATAP SHINDE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0016', 'TEJAS SONAWANE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0017', 'ROHIT DHOLE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0019', 'SARTHAK KULKARNI', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0020', 'VINAY YADAV', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0021', 'PULKIT SAINI', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0023', 'VEDIKA THALKAR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0024', 'VAIBHAV  BEDRE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0025', 'VAISHNAVI PATIL', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0026', 'HARSHAD  PATEKAR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0027', 'SHUBHAM BANEKAR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0028', 'GAUTAMI SURVE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0029', 'GAURI BAHETI', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0030', 'ASHARANI SAHU', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0033', 'SHREYA JADHAO', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0034', 'TANAY SHINDE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0035', 'KASHISH GAJBHIYE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0036', 'SAMIKSHA WANKHEDE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0037', 'NIRAJ RATHOD', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0038', 'VRUSHALI KARPE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0040', 'NIKET LOLAYEKAR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0041', 'SHRUTI DAHIVALIKAR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0042', 'VARAD MHATRE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0044', 'HARSHAL DHARADE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0046', 'NISARG AMBAWADE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0049', 'SUNNY  THAKUR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0051', 'NEERAJ  DESHMKUH', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0053', 'AARYA TAMBDE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0056', 'JITESH GAIKWAD', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0058', 'DIKSHITA PIMPALE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0059', 'NEHA DHUMAL', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0060', 'YASH PATIL', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0062', 'PARTH MOKASHI', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0063', 'AMAN SINGH', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0064', 'PUNIT JADHAV', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0066', 'SARTHAK HANKARE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0067', 'OMKAR DHAWALE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0068', 'RAUNAK BAWEJA', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0069', 'HARSHVARDHAN  POYREKAR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0070', 'RIYA THAKUR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0071', 'NIKITA NAIK', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0072', 'SHANTANU RAUT', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0073', 'OM NIKAM', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0074', 'SHREYAS DESAI', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0075', 'MADHURA PATIL', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0076', 'SAISH NALAVADE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0077', 'KHUSHALI DUKHANDE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0078', 'PURVESH TAWADE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0079', 'MOHAN LINGAMURTHY', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0080', 'ATHARVA SAWANT', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0081', 'RIYA VANAVE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0082', 'HARSH KUMBHAR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0083', 'SUDEEP BOBDE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101B0085', 'DILIP PAL', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('22101B0047', 'OM SHINDE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B2001', 'SHRUTI AVHAD', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B2002', 'DARSHAN JAIN', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B2003', 'YASH JADHAV', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B2004', 'KAUSHAL TRIVEDI', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B2005', 'CHETNA PADHI', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B2006', 'DURVESH  BHADGAONKAR', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B2007', 'SAHIL BORHADE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B2008', 'ADITYA BHANDARE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B2009', 'YASH VEKHANDE', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101B2010', 'SAMRUDDHI LAD', 'TE VI', 'B', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0002', 'MOHIT SINGH SONGRA', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0003', 'AKHIL MAHADIK', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0005', 'RUDRA DALVI', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0006', 'PRANAV WAGHMARE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0007', 'VEDANT GHODEKAR', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0008', 'TANISHQ CHAVAN', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0009', 'ATHARVA GANDHE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0010', 'ZUBIYA QUADRI', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0011', 'SUJAL JANGAM', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0012', 'ADARSH YADAV', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0014', 'VIGHNESH WAMAN', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0015', 'MAHESHWAREE TALEKAR', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0018', 'KAJAL SINGH', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0019', 'ATHRAV  JAWANJAL', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0024', 'PRAJYOT GHANEKAR', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0025', 'HRISHIKESH THAKARE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0026', 'SANCHIT ATRE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0027', 'NEERAJ SHARMA', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0028', 'OM SINGH', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0029', 'RUSHIKESH BHOR', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0030', 'SAMEED MULLA', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0031', 'AKANKSHA CHOUGULE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0034', 'HARINI PANIGRAHI', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0035', 'ADITYA DHADVE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0037', 'ADARSH DUBEY', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0038', 'ATHARVA NARINGREKAR', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0039', 'SIDDHARTH ROMAN', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0040', 'VEDANT GUPTA', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0041', 'HARSH PRAJAPATI', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0042', 'PRAPTI BHAYDE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0043', 'RAJ NAGVEKAR', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0044', 'NEHA VERMA', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0045', 'DIYANSH JAIN', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0046', 'SOUVIK ROUTH', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0047', 'ARYAN SAWANT', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0048', 'DEVASHRI PAVLE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0049', 'POOJA DIVEKAR', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0050', 'OM SHELAKE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0051', 'PRADNYA KHANSE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0052', 'YASH SAWANT', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0053', 'YOORAJ GOLE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0054', 'SAKET PALANDE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0055', 'AADARSH SHARMA', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0056', 'GAURI KAMBLE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0057', 'SHREY PATHRE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0058', 'SAHIL NARKAR', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0059', 'YUVRAJ GANDHI', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0060', 'MANINI JAISWAL', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0061', 'GAURANG  NAIK', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0062', 'NISARG MULIK', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0063', 'PARTH  KAMBLE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0064', 'DURGESH DERE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0065', 'KIRTANA SINGH', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0066', 'ATHERVA  HANDE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0067', 'SHAKIR KALU', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0068', 'SHREYASH PANDEY', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0069', 'MUSAB SAYYED', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0070', 'ADI SHETH', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0071', 'VIVEK DEORE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0072', 'MOHAMMED SHOAIB RAZA SHAIKH', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0073', 'ARNAV KHOT', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0074', 'SAI SHETTY', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0075', 'AKSHAT SHETTY', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0076', 'VEDANT PUNTAMBEKAR', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('23101C0077', 'SUDHIR GURUDU', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C2001', 'KHARADE RIYA KHARADE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C2002', 'CHOUDHARI SHIVANI CHOUDHARI', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C2003', 'JADHAV MANSI JADHAV', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C2004', 'SEJAL DHANVE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C2005', 'SIDDIQA KHAN KHAN', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C2006', 'MOHAMMED HASSAAN TOLE', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C2007', 'CHIRAG SHARMA', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C2008', 'RIYA MISHRA', 'TE VI', 'C', NOW());
INSERT INTO students (roll_no, name, program, division, created_at) VALUES ('24101C2009', 'TANYA JHA', 'TE VI', 'C', NOW());