
-- ============================================================
-- AUTO-GENERATED STUDENT SEED
-- ============================================================

BEGIN;

-- Delete existing attendance linked to students, and students
TRUNCATE public.attendance CASCADE;
TRUNCATE public.students CASCADE;

DO $$ 
DECLARE
  v_div_id UUID;
BEGIN

  -- Division: INFT-4-A
  SELECT id INTO v_div_id FROM public.divisions WHERE division_name = 'INFT-4-A' LIMIT 1;
  IF v_div_id IS NOT NULL THEN
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0002', 'SHAYAAN CHITRE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0006', 'SAMEER  JAGTAP', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0007', 'DARPAN PHADKE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0010', 'FAAEQ SAYED', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0011', 'MOHAMMED TALHA KHAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0013', 'VIRAJ BHADANGE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0014', 'ABDUL HAKIM SHAIKH', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0015', 'MAYURI KINAKE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0016', 'SACHIN YADAV', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0017', 'ABEDAN BISWAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0018', 'NAVEEN  KALDATE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0020', 'NINAD GABHALE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0021', 'TANAYA LOKHANDE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0022', 'SAIRAJ KHANDAGALE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0023', 'ABHIJEET SADAMATE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0024', 'SAYALI ANDHALE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0025', 'AMAAN SIDDIQUE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0026', 'UDAY MAHAJAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0027', 'SHIVAM  MISHRA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0028', 'MANTHAN DHOKTE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0029', 'AVINASH PADVI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0030', 'ASHWIN AMBASTHA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0031', 'SHREYA SURVE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0032', 'CHANDANI SAW', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0033', 'NIKHIL SAKPAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0034', 'YASH MORE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0035', 'SUMIT GHATUL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0036', 'ADITYA SHINDE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0037', 'SOHAM DUGADE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0038', 'AADITYA SURYAWANSHI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0039', 'ATHARV GHORPADE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0040', 'OM RATHOD', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0041', 'ABUBAKAR AHMED', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0042', 'SRUSHTI BANUGADE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0043', 'RITIK JAIN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0045', 'SHRAVNI ANDHALE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0046', 'SRUSHTI PADVI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0047', 'KAVITA GUPTA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0048', 'SANSKRUTI PALKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0049', 'SIDDHARTH  SHINDE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0050', 'CHIRAG POOJARY', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0051', 'MOHAMMAD ARHAAM SHAIKH', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0052', 'AAYUSH BHOGALE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0053', 'PRANIT WAGHMARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0054', 'MARTAND JADHAV', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0055', 'DARSHAN PALKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0056', 'ANKUR  KESARKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0057', 'OM  PAWAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0058', 'AENOSE JOEL GURRALA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0060', 'ROMIN KHAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0061', 'GAURAV GHUDE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0062', 'MUNJA KADAM', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0063', 'FARHAN AHMAD KHAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0065', 'YASH PATIL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0066', 'JENISH  SHAH', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0067', 'SWARA BIRJE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0068', 'SAMPRATI  TIKONE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0069', 'OM YEWALE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0070', 'KEDAR SAWANT', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0071', 'SAUKHYA GAIKWAD', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0072', 'LOKESH  MARATHE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0073', 'ADVAY TONGAONKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0074', 'SRUSHTI CHAVAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0075', 'AYUSH PATIL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0076', 'YASH  BAKALE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0077', 'ISHAN GURAV', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0078', 'MANTHAN SHAH', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0079', 'PREM YELWANDE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0080', 'JIYA KANOJIA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A0081', 'ADITYA DANDAGVHAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101A2001', 'DEEPALI GANACHARI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101A2002', 'SNEHAL PATIL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101A2003', 'GRISHMA PATIL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101A2004', 'TEJAL SURKULE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101A2005', 'SARTHAK SONAWANE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101A2006', 'VAISHNAVI KUNTE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101A2007', 'ANUSHKA GADHAVE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101A2008', 'TANVI JAWARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101A2009', 'SHRAVANI KADAM', 1, true);
  END IF;

  -- Division: INFT-4-B
  SELECT id INTO v_div_id FROM public.divisions WHERE division_name = 'INFT-4-B' LIMIT 1;
  IF v_div_id IS NOT NULL THEN
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0001', 'MOHAMMED YUSUF SAYED', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0004', 'GAYATRI CHAND', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0005', 'DHANRAJ MOGERA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0006', 'VARENNYA  POPHALI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0007', 'SHIVANSHU RAI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0008', 'RITESH ZAGADE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0009', 'GAURI KHATOKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0013', 'KARTIK MAILARAM', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0014', 'SAHIL SANAP', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0016', 'VAISHNAVI BAGADE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0017', 'DEVEN MAGAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0018', 'PREM RANMALE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0019', 'SWAYAM  SONAVNE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0021', 'JAGDISH  BAKLE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0022', 'SUMIT SURWASE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0023', 'SAMRUDDHI KHADE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0025', 'KRISH PATIL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0026', 'SHREESH KHAMKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0027', 'PRANITHA SHETTY', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0028', 'SUJAL TIWARI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0029', 'PRADNYA CHAUDHARI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0030', 'SARTHAK KANE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0031', 'SHRIHARI DAVARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0032', 'MRUNALI DEVARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0034', 'SHREYAS  CHOUDHARY', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0035', 'HIMANSHU CHOYAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0036', 'PARTH KINAGE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0037', 'PRIYANSHU GUPTA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0038', 'SHUBHAM MAHANWAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0040', 'VARAD DALVI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0042', 'SNEHA BHUNDERE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0043', 'OMKAR BENGALI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0044', 'RONAK BODDU', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0045', 'VIVEK KHANDARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0046', 'RASHI KHUTWAD', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0047', 'VISHAL PRAJAPATI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0048', 'MOHD ALTAMASH ANSARI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0049', 'MEET ALSHI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0051', 'VEDANGI POKHARKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0052', 'ATHARV RAUT', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0053', 'PHALGUNI DHOPTE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0054', 'IMRAN SHAIKH', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0055', 'RONAK GHODE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0056', 'AMOL PATIL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0057', 'BHUSHAN BOROLE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0058', 'ROHIT RATHOD', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0061', 'ADITYA SARKATE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0063', 'AASHUTOSH MAHAJAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0064', 'NIKHAT MOMIN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0065', 'SWAPNIL BHABAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0068', 'YASH JADHAV', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0070', 'SHARWARI LOHATE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0071', 'TANISHKA  MANTRI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0072', 'ADITYA PATRA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0073', 'ADITYA  BHOGAVKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0074', 'KRISH  GHAG', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0075', 'SNIGDHA SEEPA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0076', 'TANVEE KAMBLE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0077', 'KRISHNA TIWARI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0078', 'SHRIYA VIBHUTE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0079', 'PEARL RATHOD', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0080', 'MANTHAN RATHI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0081', 'SAIRAJ PATEKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0082', 'ATHARVA GAIKWAD', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B0083', 'MALHAAR NIKAM', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101B2001', 'SUJAL PATIL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101B2002', 'ADARSH RASAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101B2003', 'VIBHAS KADAM', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101B2004', 'VEDANT SAKPAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101B2005', 'SNEHA MAHADIK', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101B2006', 'BHUSHAN AVHAD', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101B2007', 'SHREEDHAR KHORATE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101B2008', 'IFFAT KHAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101B2009', 'SIMRAN WAGHMARE', 1, true);
  END IF;

  -- Division: INFT-4-C
  SELECT id INTO v_div_id FROM public.divisions WHERE division_name = 'INFT-4-C' LIMIT 1;
  IF v_div_id IS NOT NULL THEN
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0002', 'SHREEMAN KUMAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0003', 'OMKAR  PADHI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0004', 'DARSHAN KERKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0006', 'ATHARVA CHAVAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0007', 'MRUNAL WARANGE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0008', 'ATHARVA BHOSALE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0010', 'VEDANT CHAVAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0011', 'SAKSHI ROUNDHAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0013', 'BURHANUDDIN LOKHANDWALA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0014', 'SHREYA MURKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0015', 'ASHWIN AGRAWAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0016', 'NEHA NAYAK', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0017', 'ANKITA SHANBHAG', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0018', 'SHWETA GUPTA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0019', 'SHRIYA  SAWANT', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0020', 'ARYAN KELKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0021', 'PRATHAMESH SALUNKHE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0022', 'ARYAN ACHARYA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0024', 'PRANAY  UPADHYAY', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0025', 'ROHAN SINGH', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0026', 'SUSHANT NIRATE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0027', 'DAKSH PARDESHI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0030', 'HUZAIFAH SHAIKH', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0031', 'RITIKA SHARMA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0032', 'JAYA PATIL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0033', 'DEVANGINI JADHAV', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0034', 'AAYUSH ABHYANKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0035', 'JAY  JADHAV', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0036', 'SHANTANU DALVI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0037', 'HARSH SURANA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0038', 'SHLOK JAIN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0039', 'ASHUTOSH TRIPATHI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0040', 'SAURABH  LUBAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0041', 'OM THAKUR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0042', 'SAKSHI JADHAV', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0043', 'RAHUL AMBHORE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0044', 'SUBHADEEP MONDAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0045', 'SHARVIL CHANDURKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0046', 'PUSHKAR CHAVAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0048', 'GAUTAM KESHARWANI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0051', 'GAURAV TIWARI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0052', 'KHUSH JAIN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0053', 'VIVEK RAMINA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0054', 'SAWANKUMAR GUPTA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0056', 'ASAWARI NAVLE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0057', 'RUHAAN JOSHI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0058', 'SARTHAK BONGANE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0059', 'KASHYAP SAKHARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0060', 'JASWANDI VICHARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0061', 'PRANAY BELNEKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0062', 'RUDRA JAIN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0063', 'SHLOK SHINDE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0064', 'NIRMITI SAWANT', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0065', 'AYUSH KAMBLE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0066', 'SHAMITA  CHAVAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0067', 'DURVA MALUSARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0068', 'VARUN SINGH', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0069', 'DEVANSH DHAWADE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0070', 'ANAGHA VICHARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0071', 'ADITYA  KANNOJIYA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0072', 'PRERNA CHAVAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0073', 'AARUSH NALAVADE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0074', 'MRUNALI PATIL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0075', 'SHAAN JANA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0076', 'SHUBHAM SINGH', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0077', 'VEDANT TULASKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C0078', 'DAKSH MALUSKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101C2001', 'ESHA VALUNJ', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101C2002', 'JUVERIYA KHAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101C2003', 'RISHABH MAHADIK', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101C2004', 'DNYANESHWARI GADADHE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101C2005', 'NAMAN MEHTA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101C2006', 'RUSHIKA GAIKWAD', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '25101C2007', 'VIVEK TANDEL', 1, true);
  END IF;

  -- Division: INFT-6-A
  SELECT id INTO v_div_id FROM public.divisions WHERE division_name = 'INFT-6-A' LIMIT 1;
  IF v_div_id IS NOT NULL THEN
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0001', 'MAYANK EKBOTE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0002', 'PRANJALI NANDKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0005', 'NIRANJANA CHAVAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0006', 'ARYAN DALAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0007', 'SANKHYA LONDHE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0008', 'SWAYAM BALLAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0009', 'VED THOMBRE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0010', 'SOHAM WAYANGANKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0011', 'AMAN VARMA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0012', 'TEJAS KHANDARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0013', 'SARVESH CHOUDHARY', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0014', 'JALAJA YELVE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0015', 'ARUNIMA PILLAI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0016', 'AKANKSHA JADHAV', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0017', 'SOHAN BHANGARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0018', 'SUJAL JAKAKURE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0019', 'ROHIT GUPTA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0020', 'BUSHRA SAEED', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0021', 'ALOK MESHRAM', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0022', 'ARYANT  JADHAV', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0023', 'KASHYAP NATHOO', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0024', 'RITESH PAWAR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0025', 'ANSH  KUDALKAR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0026', 'RITIKA VARADKAR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0027', 'DIKSHA VAREKAR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0028', 'KAMRAAN MULANI', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0029', 'SHUBHAM YADAV', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0030', 'OMPRAKASH MAURYA', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0031', 'SHUBHAM GAJARE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0032', 'SHREYA GAONKAR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0033', 'SHREYAS KHOBRAGADE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0034', 'KANHAIYALAL YADAV', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0035', 'ARADHYA JADHAV', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0036', 'ATHARV JADHAV', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0037', 'TEJAS SHINGTE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0038', 'DEVEN BAGADE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0039', 'KIRAT SINGH CHAWLA', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0041', 'ARYAN VARMA', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0042', 'ASMITA PAL', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0043', 'ATHARVA KENI', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0045', 'ATHARVA DESHMUKH', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0047', 'SHARWAN SHINGADE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0048', 'ABHISHEK WALI', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0049', 'SAIF SIDDIQUI', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0050', 'JATIN RATHOD', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0051', 'YASHODHAN RAJAPKAR', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0052', 'YADNIKA PASHTE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0053', 'CHAITRALI  MITHBAWKAR', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0054', 'AYUSH SHEWALE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0055', 'HARSHAD KANERKAR', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0056', 'SHREYAS KHARAT', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0059', 'AARYA KHAIRE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0060', 'PRITRAJ CHAUDHARY', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0061', 'SAIRAJ NAIKDHURE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0062', 'SHUBHAM WAVRE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0063', 'SARTHAK GAIKAR', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0064', 'MANORANJAN PAUL', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0065', 'RISHABH HEGDE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0067', 'KAIVALYA GHARAT', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0068', 'OMKAR MADAV', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0070', 'VIGHNARAJENDRA  KAKADE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0071', 'AYUSH GUJAR', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0072', 'PRITIVARDHINI SANGAVE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0073', 'SWARALI MAHISHI', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0074', 'TANAYA SALUNKE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0075', 'SWAYAM PAWAR', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0076', 'DEVEN HADKAR', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101A0077', 'ISHWARI PANDIT', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23102A0051', 'SOHAM PAWAR', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23108A0031', 'IRA VAIDYA', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A2001', 'ATHARVA GITAYE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A2002', 'APURV DESHMUKH', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A2003', 'PRITI CHAVAN', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A2004', 'SWATI MANE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A2005', 'ANISH BANDAL', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A2006', 'VIPUL RAGHATWAN', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A2007', 'MUKTA REDIJ', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A2008', 'ARYAN CHAVAN', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A2009', 'ADITYA MULEY', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101A2010', 'ANKITA PAWAR', 4, true);
  END IF;

  -- Division: INFT-6-B
  SELECT id INTO v_div_id FROM public.divisions WHERE division_name = 'INFT-6-B' LIMIT 1;
  IF v_div_id IS NOT NULL THEN
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0002', 'VISHANT GAWALI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0003', 'KESHAV VERMA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0004', 'SAMIKSHA DALVI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0005', 'DHRUV TIKHANDE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0006', 'ISHWAR GARJE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0007', 'SNEHA AJAGEKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0008', 'MADHUR PATIL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0009', 'JAY  JANGAM', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0010', 'ATHARV PETKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0011', 'OM KHEDKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0012', 'SOHAM THAKUR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0013', 'AKASH MISALE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0014', 'ZAYAN SHAIKH', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0015', 'RUDRAPRATAP SHINDE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0016', 'TEJAS SONAWANE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0017', 'ROHIT DHOLE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0019', 'SARTHAK KULKARNI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0020', 'VINAY YADAV', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0021', 'PULKIT SAINI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0023', 'VEDIKA THALKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0024', 'VAIBHAV  BEDRE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0025', 'VAISHNAVI PATIL', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0026', 'HARSHAD  PATEKAR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0027', 'SHUBHAM BANEKAR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0028', 'GAUTAMI SURVE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0029', 'GAURI BAHETI', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0030', 'ASHARANI SAHU', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0033', 'SHREYA JADHAO', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0034', 'TANAY SHINDE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0035', 'KASHISH GAJBHIYE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0036', 'SAMIKSHA WANKHEDE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0037', 'NIRAJ RATHOD', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0038', 'VRUSHALI KARPE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0040', 'NIKET LOLAYEKAR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0041', 'SHRUTI DAHIVALIKAR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0042', 'VARAD MHATRE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0044', 'HARSHAL DHARADE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0046', 'NISARG AMBAWADE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0049', 'SUNNY  THAKUR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0051', 'NEERAJ  DESHMKUH', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0053', 'AARYA TAMBDE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0056', 'JITESH GAIKWAD', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0058', 'DIKSHITA PIMPALE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0059', 'NEHA DHUMAL', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0060', 'YASH PATIL', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0062', 'PARTH MOKASHI', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0063', 'AMAN SINGH', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0064', 'PUNIT JADHAV', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0066', 'SARTHAK HANKARE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0067', 'OMKAR DHAWALE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0068', 'RAUNAK BAWEJA', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0069', 'HARSHVARDHAN  POYREKAR', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0070', 'RIYA THAKUR', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0071', 'NIKITA NAIK', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0072', 'SHANTANU RAUT', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0073', 'OM NIKAM', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0074', 'SHREYAS DESAI', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0075', 'MADHURA PATIL', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0076', 'SAISH NALAVADE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0077', 'KHUSHALI DUKHANDE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0078', 'PURVESH TAWADE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0079', 'MOHAN LINGAMURTHY', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0080', 'ATHARVA SAWANT', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0081', 'RIYA VANAVE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0082', 'HARSH KUMBHAR', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0083', 'SUDEEP BOBDE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101B0085', 'DILIP PAL', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '22101B0047', 'OM SHINDE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B2001', 'SHRUTI AVHAD', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B2002', 'DARSHAN JAIN', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B2003', 'YASH JADHAV', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B2004', 'KAUSHAL TRIVEDI', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B2005', 'CHETNA PADHI', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B2006', 'DURVESH  BHADGAONKAR', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B2007', 'SAHIL BORHADE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B2008', 'ADITYA BHANDARE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B2009', 'YASH VEKHANDE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101B2010', 'SAMRUDDHI LAD', 4, true);
  END IF;

  -- Division: INFT-6-C
  SELECT id INTO v_div_id FROM public.divisions WHERE division_name = 'INFT-6-C' LIMIT 1;
  IF v_div_id IS NOT NULL THEN
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0002', 'MOHIT SINGH SONGRA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0003', 'AKHIL MAHADIK', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0005', 'RUDRA DALVI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0006', 'PRANAV WAGHMARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0007', 'VEDANT GHODEKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0008', 'TANISHQ CHAVAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0009', 'ATHARVA GANDHE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0010', 'ZUBIYA QUADRI', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0011', 'SUJAL JANGAM', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0012', 'ADARSH YADAV', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0014', 'VIGHNESH WAMAN', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0015', 'MAHESHWAREE TALEKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0018', 'KAJAL SINGH', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0019', 'ATHRAV  JAWANJAL', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0024', 'PRAJYOT GHANEKAR', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0025', 'HRISHIKESH THAKARE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0026', 'SANCHIT ATRE', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0027', 'NEERAJ SHARMA', 1, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0028', 'OM SINGH', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0029', 'RUSHIKESH BHOR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0030', 'SAMEED MULLA', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0031', 'AKANKSHA CHOUGULE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0034', 'HARINI PANIGRAHI', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0035', 'ADITYA DHADVE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0037', 'ADARSH DUBEY', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0038', 'ATHARVA NARINGREKAR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0039', 'SIDDHARTH ROMAN', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0040', 'VEDANT GUPTA', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0041', 'HARSH PRAJAPATI', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0042', 'PRAPTI BHAYDE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0043', 'RAJ NAGVEKAR', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0044', 'NEHA VERMA', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0045', 'DIYANSH JAIN', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0046', 'SOUVIK ROUTH', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0047', 'ARYAN SAWANT', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0048', 'DEVASHRI PAVLE', 2, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0049', 'POOJA DIVEKAR', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0050', 'OM SHELAKE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0051', 'PRADNYA KHANSE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0052', 'YASH SAWANT', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0053', 'YOORAJ GOLE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0054', 'SAKET PALANDE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0055', 'AADARSH SHARMA', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0056', 'GAURI KAMBLE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0057', 'SHREY PATHRE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0058', 'SAHIL NARKAR', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0059', 'YUVRAJ GANDHI', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0060', 'MANINI JAISWAL', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0061', 'GAURANG  NAIK', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0062', 'NISARG MULIK', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0063', 'PARTH  KAMBLE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0064', 'DURGESH DERE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0065', 'KIRTANA SINGH', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0066', 'ATHERVA  HANDE', 3, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0067', 'SHAKIR KALU', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0068', 'SHREYASH PANDEY', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0069', 'MUSAB SAYYED', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0070', 'ADI SHETH', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0071', 'VIVEK DEORE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0072', 'MOHAMMED SHOAIB RAZA SHAIKH', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0073', 'ARNAV KHOT', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0074', 'SAI SHETTY', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0075', 'AKSHAT SHETTY', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0076', 'VEDANT PUNTAMBEKAR', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '23101C0077', 'SUDHIR GURUDU', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C2001', 'KHARADE RIYA KHARADE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C2002', 'CHOUDHARI SHIVANI CHOUDHARI', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C2003', 'JADHAV MANSI JADHAV', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C2004', 'SEJAL DHANVE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C2005', 'SIDDIQA KHAN KHAN', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C2006', 'MOHAMMED HASSAAN TOLE', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C2007', 'CHIRAG SHARMA', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C2008', 'RIYA MISHRA', 4, true);
    INSERT INTO public.students (division_id, roll_number, full_name, batch_number, is_active) VALUES (v_div_id, '24101C2009', 'TANYA JHA', 4, true);
  END IF;

END $$;
COMMIT;
